name: flutter_embed_unity_2022_3_android
description: Android implementation for Unity 2022.3 LTS of the flutter_embed_unity plugin.
version: 1.1.0
homepage: https://learntoflutter.com
repository: https://github.com/learntoflutter/flutter_embed_unity/tree/main/flutter_embed_unity_2022_3_android
issue_tracker: https://github.com/learntoflutter/flutter_embed_unity/issues
documentation: https://github.com/learntoflutter/flutter_embed_unity/wiki
funding:
  - https://www.buymeacoffee.com/pPDtNs6A6T
topics:
  - unity

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_embed_unity_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_embed_unity
    platforms:
      android:
        package: com.learntoflutter.flutter_embed_unity_android
        pluginClass: FlutterEmbedUnityAndroidPlugin